### ISSUE TITLE
More simple golangci-lint configuration

### ISSUE THREAD

**Issue by KEINOS** [KEINOS/Hello-Cobra#40]
The [current configuration for `golangci-lint`](https://github.com/KEINOS/Hello-Cobra/blob/c481de75ad3985edd618fe5e200bda93601d5cfc/.golangci.yml) is not versatile.

It is hard to read and also contains deprecated and/or un-maintained linters as well. If we want a strong configuration by default, we should **simply `enable-all` and disable deprecated linters**.

The "allowed-list" style is more readable and easier to maintain. Here's the full sample YAML.

```yaml
run:
  tests: true
  fast: true
  build-tags:
    - golangci
  skip-dirs:
    - .github
  allow-parallel-runners: true

output:
  format: colored-line-number
  sort-results: true

linters:
  enable-all: true
  disable:
  # Deprecated linters
  - exhaustivestruct
  - golint
  - ifshort
  - interfacer
  - maligned
  - scopelint
```
