### ISSUE TITLE
Use matrix on actions

### ISSUE THREAD

**Issue by KEINOS** [KEINOS/Hello-Cobra#48]
As shown below, using `matrix`, we can simplify tests on various Go versions even via container.

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.13' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go run hello.go
```
